reporter: "xcode"
line_length:
  - 200
  - 500
file_length:
  - 600
  - 2000
cyclomatic_complexity:
  - 20
type_body_length:
  - 400
variable_name:
  min_length:
    - 1
  max_length:
    - 60
excluded:
  - Tests
  - "*Tests"
  - Pods
  - localPods
  - Submodules
disabled_rules:
  - trailing_newline
  - nesting
  - type_name
