reporter: "xcode"
line_length:
  - 200
  - 500
file_length:
  - 600
  - 2000
cyclomatic_complexity:
  - 20
type_body_length:
  - 400

force_cast: warning
force_try:
  severity: warning
shorthand_operator:
  severity: warning

identifier_name:
  severity: warning
  min_length:
    - 1
  max_length:
    - 60

excluded:
  - Tests
  - "*Tests"
  - Pods
  - Submodules
disabled_rules:
  - trailing_newline
  - nesting
  - type_name
