use_frameworks!

target 'tuva-core-example' do
  platform :ios, '12.0'
  pod 'TuvaCore', :path => '../'

  #linters
   pod 'SwiftFormat/CLI'
   pod 'SwiftLint'

   script_phase :name => 'Swiftformat', :script => ' ./Pods/SwiftFormat/CommandLineTool/swiftformat .', :execution_position => :before_compile
   script_phase :name => 'SwiftLint', :script => ' ./Pods/SwiftLint/swiftlint', :execution_position => :before_compile
   script_phase :name => 'SwiftLint Pod', :script => 'cd ../Sources/TuvaCore && ../../Example/Pods/SwiftLint/swiftlint', :execution_position => :before_compile
   script_phase :name => 'Swiftformat Pod', :script => './Pods/SwiftFormat/CommandLineTool/swiftformat ../Sources/TuvaCore', :execution_position => :before_compile

  target 'tuva-core-tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end

target 'tuva-core-mos-example' do
  platform :macos, '10.15'

  pod 'TuvaCore', :path => '../'

  #linters
   pod 'SwiftFormat/CLI'
   pod 'SwiftLint'

   script_phase :name => 'Swiftformat', :script => ' ./Pods/SwiftFormat/CommandLineTool/swiftformat .', :execution_position => :before_compile
   script_phase :name => 'SwiftLint', :script => ' ./Pods/SwiftLint/swiftlint', :execution_position => :before_compile
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        if Gem::Version.new('9.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
  end
end